name: deepblue

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - python-dotenv
  - gitpython

  - pre-commit

  - ipykernel
  - ipympl
  - nbformat

  - streamlit=1.45.1

  - numpy=2.2.5
  - pandas=2.2.3
  - openpyxl=3.1.5
  - scipy=1.15.2
